# Generated by Django 4.0.4 on 2023-05-02 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food_viser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('age', models.IntegerField()),
                ('height', models.IntegerField()),
                ('gender', models.CharField(max_length=6)),
                ('activity_level', models.CharField(max_length=10)),
                ('goal', models.CharField(max_length=8)),
                ('food_items', models.CharField(max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='NutritionProfile',
        ),
    ]
