# Generated by Django 4.0.4 on 2023-05-01 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_nutritionprofile_delete_uploadimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NutritionProfile',
        ),
    ]
