# Generated by Django 4.0.4 on 2023-05-02 07:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_alter_nutritionprofile_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NutritionProfile',
            new_name='Nutrition',
        ),
    ]
